version: '2'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    ports:
      - 2181:2181
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    links:
      - zookeeper1
    depends_on:
      - zookeeper1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_CREATE_TOPICS: "TOPIC1:10:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper2:
      image: wurstmeister/zookeeper
      container_name: zookeeper2
      ports:
        - 2182:2181
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    links:
      - zookeeper2
    depends_on:
      - zookeeper2
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_CREATE_TOPICS: "TOPIC1_DIFFERENT:10:1,TOPIC2_DIFFERENT:20:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kiwi:
    image: dmwood/kiwi:latest
    container_name: kiwi
    ports:
      - 8090:8080
    links:
      - zookeeper1
      - zookeeper2
      - kafka1
      - kafka2
    depends_on:
      - zookeeper1
      - zookeeper2
      - kafka1
      - kafka2
    environment:
      KAFKA_BASE_PRODUCER_ACKS: all
      KAFKA_CLUSTERS_CLUSTERONE_CLIENT_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_CLUSTERTWO_CLIENT_BOOTSTRAPSERVERS: kafka2:9092
      KAFKA_CLUSTERS_CLUSTERTWO_CONSUMER_MAXPOLLRECORDS: 600
      KAFKA_DEFAULTCLUSTERNAME: clusterone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

